// <auto-generated />
using System;
using Chatty.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chatty.Infrastructure.Migrations
{
    [DbContext(typeof(ChattyDbContext))]
    [Migration("20231007155154_chatty_users_table")]
    partial class chatty_users_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Chatty.ApplicationCore.Entities.ChattyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreatedAtGmt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_gmt");

                    b.Property<int>("Deleted")
                        .HasColumnType("int")
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UpdatedAtGmt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_gmt");

                    b.HasKey("Id");

                    b.ToTable("chatty_users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
